### ISSUE TITLE
Novos títulos legais

### ISSUE THREAD

**Issue by alvesleonardo** [opensanca/recommended_books#4]
Segue a lista de alguns livros legais para inserir na lista.
The Pragmatic Programmer, From Journeyman to Master
Growing Object-Oriented Software Guided by Tests
Clojure for the Brave and True (Este livro é gratuíto, e tem um capítulo sobre programação funcional que pode ajudar em relação ao código procedural)

**Comment by duduribeiro** [comment]
Opa @alvesleonardo, vlww pelas sugestōes \o/

tem como escrever um pequeno comentário para cada um dos livros:

ex: Clean Code: 

```
Comentários:
Um livro que deve estar presente com todos desenvolvedores que prezam por qualidade de software. Um livro com ótimos conselhos e exemplos de como e por que devemos escrever um código limpo e como evitar os "maus cheiros" de nosso código.
```

**Comment by alvesleonardo** [comment]
Fala eduardo, desculpa a demora em fazer os resumos. Mas seguem eles. 
- The Pragmatic Programmer, From Journeyman to Master: Um texto mais voltado a iniciantes. Nesse livro pode-se encontrar as práticas que sempre são ignoradas como usar controle de versão para tudo, preferir formatos de texto puro e dominar um ambiente de linha de comando. Além disso há discussões sobre como organizar equipes, sobre linguagens específicas de domínio e o mundialmente famoso princípio DRY (Don't Repeat Yourself).
- Growing Object-Oriented Software Guided by Tests: Um livro sobre TDD (Test-Driven Development), mostrando a importância de se criar os testes antes mesmo de se iniciar o desenvolvimento. O livro mostra um processo para criação de softwares escaláveis e coesos bem como algumas ferramentas que podem ajudar nesse processo.
- Clojure for the Brave and True: Um livro que passa do básico ao avançado na programação funcional. Esse livro é uma leitura obrigatória não somente para quem quer aprender a programar em Clojure, mas para quem quer entender melhor o paradigma funcional.

**Comment by duduribeiro** [comment]
Adicionado. Vlww @alvesleonardo 
:beers:
